### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by vaibhavn1** [Justin-Credible/cordova-plugin-yozio#2]
Hi team,

Looks like a great service. Could you post one example showing all the features.

Regards

Wiki

**Comment by Justin-Credible** [comment]
What specifically are you looking for?

The readme goes over all of the available functions, and there is a TypeScript definition file in the typings directory that documents each method.

If you are looking for more information on the Yozio service, you can check http://docs.yozio.com/

**Comment by Justin-Credible** [comment]
I don't think a sample project is very useful for this plugin because how the way Yozio data is used will differ between applications. Basically, after device resume you can call any of the methods this plugin provides so you can retrieve the installation and deep link metdata.

I'm going to close this for now. Let me know if you feel anything is missing or lacking clarification in the documentation.

**Comment by vaibhavn1** [comment]
Sorry man , was travelling so couldnt reply. I think sample wont be required for now , if i need any assistance i will get in touch with you .
